# .github/workflows/cicd.yml

# - push to ECR   ---
# - Run the container on EC2/ECS   ---

name: cicd pipeline
on:
  push:
    branches:
      - main
    paths:                # if any changes detected in below dir then runner'll trigger cicd pipeline
      - ./src/**
      - .github/**
      - ./prod/**
      - Dockerfile
      - docker_requirements.txt
  pull_request: 
    branches:
      - main

jobs:
  download_model:   
    name: download latest prod model         
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Install AWS CLI      # install aws cli in runner space
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure AWS CLI    # configure aws cli so that we can access there services via cmd line or scripts
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_REGION }}

      - name: Install Utilities     # install utilities required to fetch model from backend
        run: |
            python -m pip install --upgrade pip
            if [ -f model_requirements.txt ]; then pip install -r model_requirements.txt; fi 

      - name: Fetch Model From Mlflow   # below script will executed and fetch the prod model
        run: |
          python ./prod/mlflowdb.py ${{ secrets.TRACKING_URI }}
      
      - name: Upload Model Artifact            # save the artifacts so that we can utilise it in next stage     
        uses: actions/upload-artifact@v2
        with:
          name: model
          # in path give correct repository name as here "cicd-aws/cicd-aws" 
          path: | 
            /home/runner/work/cicd-aws/cicd-aws/model.joblib    
            /home/runner/work/cicd-aws/cicd-aws/model_details.json

      - name: Print Current Directory          # for debuging purpoer, u can remove it
        run: ls /home/runner/work/cicd-aws/cicd-aws

  build_push_docker_image:  
    name: build & push to ECR   
    needs: download_model      # previous stage must be successfully completed (job dependency)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Current Directory be-down       # for debug purpose
        run: ls /home/runner/work/cicd-aws/cicd-aws

      - name: Download Model Artifacts           # download the previously saved artifacts
        uses: actions/download-artifact@v2
        with:
          name: model
          path: /home/runner/work/cicd-aws/cicd-aws
      
      - name: Print Current Directory af-down     # for debugging
        run: ls /home/runner/work/cicd-aws/cicd-aws

      # push img to ECR
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Aws ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ secrets.REGISTRY }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
